import './globals.css'
import NavBar from "@/components/NavBar/NavBar";


export const metadata = {
    title: 'Факультеты',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className='container flex gap-x-[25px]'>
            <div className={"w-[250px] hidden desktop:block"}>
                <NavBar/>
            </div>
            {children}
        </body>
        </html>
    )
}